name = "compliance-autopilot-license"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = true
preview_urls = false

[[kv_namespaces]]
binding = "LICENSES"
id = "a1087f5e6fcb488fa4744db4f83be03e"
